import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  const theme = localStorage.getItem('theme');
                  const root = document.documentElement;
                  if (theme === 'dark') {
                    root.style.setProperty('--background', '#0a0a0a');
                    root.style.setProperty('--foreground', '#ededed');
                  } else {
                    root.style.setProperty('--background', '#ffffff');
                    root.style.setProperty('--foreground', '#171717');
                  }
                } catch(e) {}
              })();
            `,
          }}
        />
      </head>
      <body className={''}>
        {children}
      </body>
    </html>
  )
}
