import { golos } from '@/assests/fonts'
import { Header } from '@/components/structure/Header/Header'

import type { Metadata } from 'next'

import 'bootstrap/dist/css/bootstrap.min.css'
import '@/assests/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={golos.variable}>
        <Header />
        {children}
      </body>
    </html>
  )
}
