import { golos } from '@/assests/fonts'
import { Header } from '@/components/structure/Header/Header'

import type { Metadata } from 'next'

import 'bootstrap/dist/css/bootstrap.min.css'
import '@/assests/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Применён suppressHydrationWarning, чтобы скрыть предупреждение о гидрации из-за установки темы. В рамках текущего проекта без styled-components и сложного UI такой подход считается допустимым и не вызывает побочных эффектов
    // <html lang="en" suppressHydrationWarning>
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  const theme = localStorage.getItem('theme');
                  const root = document.documentElement;
                  if (theme === 'dark') {
                    root.style.setProperty('--background', '#0a0a0a');
                    root.style.setProperty('--foreground', '#ededed');
                  } else {
                    root.style.setProperty('--background', '#ffffff');
                    root.style.setProperty('--foreground', '#171717');
                  }
                } catch(e) {}
              })();
            `,
          }}
        />
      </head>
      <body className={golos.variable}>
        <Header />
        {children}
      </body>
    </html>
  )
}
